language: go
go:
  - 1.7
  - 1.8
  - 1.9
install: 
    - go get -v github.com/Masterminds/glide
    - cd $GOPATH/src/github.com/Masterminds/glide 
    - go install 
    - cd -
    - glide install
    - go get -v ./
script:
    - go test -v -race ./...